### PR TITLE
suggested fix

### PR DESCRIPTION
**Pull request by Robbie1977**
Ref https://github.com/jefferis/vfbr/issues/10#issuecomment-412970428

### CODE REVIEW

**Comment by Robbie1977** [comment]
@jefferis Fixed takes TRUE or FALSE

**Comment by Robbie1977** [comment]
@jefferis needs a more fundamental fix so it returns null at least so the numbers match up.

**Comment by Robbie1977** [comment]
@jefferis also only one id per label as GMR_10A0* returns multiple ids (correctly) but shouldn't happen in this context (vfb_tovfbids) just return the first is a safer way to handle it.

**Comment by jefferis** [comment]
Sorry I had another commit unpushed that should address this. Can you try latest master?

**Pull request closed without merging**
